import NavBar from "@/components/arb/NavBar";
import { FooterComponent } from "@/components/arb/FooterComponent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "طارق لویس",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div style={{ direction: "rtl" }}>
      <NavBar />
      <div className="p-3">{children}</div>
      <FooterComponent />
    </div>
  );
}
