import type { Metadata } from "next";
import NavBar from "@/components/en/NavBar";
import { FooterComponent } from "@/components/en/FooterComponent";

export const metadata: Metadata = {
  title: "Tariq Louis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar />
      {children}
      <FooterComponent />
    </>
  );
}
